workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    agentic:
        inputs:
            - location: ./specs/agentic.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/compose-market/compose-market/agentic
    inference:
        inputs:
            - location: ./specs/inference.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/compose-market/compose-market/inference
    x402:
        inputs:
            - location: ./specs/x402.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/compose-market/compose-market/x-402
targets:
    agentic:
        target: typescript
        source: agentic
        output: ./generated/agentic
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/compose-market/compose-market/agentic-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
    inference:
        target: typescript
        source: inference
        output: ./generated/inference
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/compose-market/compose-market/inference-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
    x402:
        target: typescript
        source: x402
        output: ./generated/x402
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/compose-market/compose-market/x-402-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
